[package]
name = "amanuensis-cli"
version = "0.2.4"
edition = "2021"

[[bin]]
name = "amanuensis"
path = "src/main.rs"

[dependencies]
amanuensis-core = { path = "../amanuensis-core" }
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
comfy-table = "7"
log = "0.4"
