[package]
name = "scribius-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "scribius"
path = "src/main.rs"

[dependencies]
scribius-core = { path = "../scribius-core" }
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
comfy-table = "7"
log = "0.4"
